import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useHelloWorld } from '@frontend/shared/hooks/hellow/hellow';
import { HELLO } from '@frontend/shared/graphql/query/auth';
import { useQuery } from '@apollo/client';
import { Hello } from '../components/Hello';

const Home: NextPage = () => {
  // const { data, error, loading } = useHelloWorld();
  // const { data, error, loading, subscribeToMore } = useQuery(HELLO, {
  //   variables: {},
  //   fetchPolicy: 'cache-and-network',
  // });
  // console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello World</h1>

        <div>
          <Hello />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
